package Vista;
import javax.swing.border.*;

/**
 *
 * @RolandoEscobar
 */
public class MainUI extends javax.swing.JFrame {

    /** Creates new form MainUI */
    public MainUI() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Gestión Ventas ALL YOU WEED IS LOVE");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        btn_mod3 = new javax.swing.JButton();
        btn_mod1 = new javax.swing.JButton();
        btn_mod4 = new javax.swing.JButton();
        btn_mod5 = new javax.swing.JButton();
        btn_mod2 = new javax.swing.JButton();
        lab_mainUI_title = new javax.swing.JLabel();
        lab_mainUI_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 0));
        setForeground(new java.awt.Color(0, 51, 0));

        panel_fondo.setBackground(new java.awt.Color(0, 51, 0));
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mod3.setBackground(new java.awt.Color(51, 153, 0));
        btn_mod3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btn_mod3.setForeground(new java.awt.Color(255, 255, 255));
        btn_mod3.setText("Módulo 3 (Gestión de Ventas)");
        panel_fondo.add(btn_mod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 210, 312, 131));

        btn_mod1.setBackground(new java.awt.Color(51, 153, 0));
        btn_mod1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btn_mod1.setForeground(new java.awt.Color(255, 255, 255));
        btn_mod1.setText("Módulo 1 (Mantenedor de información)");
        btn_mod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mod1ActionPerformed(evt);
            }
        });
        panel_fondo.add(btn_mod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 61, 312, 131));

        btn_mod4.setBackground(new java.awt.Color(51, 153, 0));
        btn_mod4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btn_mod4.setForeground(new java.awt.Color(255, 255, 255));
        btn_mod4.setText("Módulo 4 (Gestión de Clientes)");
        panel_fondo.add(btn_mod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 210, 312, 131));

        btn_mod5.setBackground(new java.awt.Color(51, 153, 0));
        btn_mod5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btn_mod5.setForeground(new java.awt.Color(255, 255, 255));
        btn_mod5.setText("Módulo 5 (Vendedores)");
        panel_fondo.add(btn_mod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 359, 312, 131));

        btn_mod2.setBackground(new java.awt.Color(51, 153, 0));
        btn_mod2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btn_mod2.setForeground(new java.awt.Color(255, 255, 255));
        btn_mod2.setText("Módulo 2 (Venta de Productos)");
        panel_fondo.add(btn_mod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 61, 312, 131));

        lab_mainUI_title.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lab_mainUI_title.setForeground(new java.awt.Color(255, 255, 255));
        lab_mainUI_title.setText("420 BLAZE IT NI**A SMOKE WEED EVERYDAY");
        panel_fondo.add(lab_mainUI_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 662, 44));

        lab_mainUI_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_mainUI_background.setText("jLabel1");
        panel_fondo.add(lab_mainUI_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mod1ActionPerformed
        //Modulo1 mod1 = new Modulo1();
        //mod1.setVisible(true);
    }//GEN-LAST:event_btn_mod1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_mod1;
    public javax.swing.JButton btn_mod2;
    public javax.swing.JButton btn_mod3;
    public javax.swing.JButton btn_mod4;
    public javax.swing.JButton btn_mod5;
    private javax.swing.JLabel lab_mainUI_background;
    private javax.swing.JLabel lab_mainUI_title;
    private javax.swing.JPanel panel_fondo;
    // End of variables declaration//GEN-END:variables

}
