/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author usuario
 */
public class Modulo2 extends javax.swing.JFrame {

    /**
     * Creates new form Modulo2
     */
    public Modulo2() {
        initComponents();
    }
    
    public void llenarBoleta(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_venta_tituloVenta = new javax.swing.JPanel();
        lab_venta_ventaProducto = new javax.swing.JLabel();
        panel_venta_cartas = new javax.swing.JPanel();
        card_seleccione = new javax.swing.JPanel();
        lab_seleccione_seleccioneCliente = new javax.swing.JLabel();
        lab_seleccione_seleccioneProducto = new javax.swing.JLabel();
        btn_seleccione_cancelar = new javax.swing.JButton();
        btn_seleccione_continuar = new javax.swing.JButton();
        separador_seleccione = new javax.swing.JSeparator();
        jScrollPane_venta_contenedorTablaClientes = new javax.swing.JScrollPane();
        table_venta_clientes = new javax.swing.JTable();
        jScrollPane_venta_contenedorTablaProducto = new javax.swing.JScrollPane();
        table_venta_productos = new javax.swing.JTable();
        lab_productos_background3 = new javax.swing.JLabel();
        card_confirme = new javax.swing.JPanel();
        lab_confirme_resumenVenta = new javax.swing.JLabel();
        jScrollPane_venta_contenedorTxtArea = new javax.swing.JScrollPane();
        txtArea_resumen = new javax.swing.JTextArea();
        btn_confirme_atras = new javax.swing.JButton();
        btn_confirme_terminarVenta = new javax.swing.JButton();
        lab_confirme_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_venta_tituloVenta.setBackground(new java.awt.Color(0, 102, 0));
        panel_venta_tituloVenta.setOpaque(false);

        lab_venta_ventaProducto.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        lab_venta_ventaProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_venta_ventaProducto.setText("Venta de producto");

        javax.swing.GroupLayout panel_venta_tituloVentaLayout = new javax.swing.GroupLayout(panel_venta_tituloVenta);
        panel_venta_tituloVenta.setLayout(panel_venta_tituloVentaLayout);
        panel_venta_tituloVentaLayout.setHorizontalGroup(
            panel_venta_tituloVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_venta_tituloVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_venta_ventaProducto)
                .addGap(0, 0, 0))
        );
        panel_venta_tituloVentaLayout.setVerticalGroup(
            panel_venta_tituloVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_venta_tituloVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_venta_ventaProducto)
                .addGap(10, 10, 10))
        );

        getContentPane().add(panel_venta_tituloVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        panel_venta_cartas.setBackground(new java.awt.Color(0, 102, 0));
        panel_venta_cartas.setLayout(new java.awt.CardLayout());

        card_seleccione.setBackground(new java.awt.Color(0, 102, 0));
        card_seleccione.setOpaque(false);
        card_seleccione.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_seleccione_seleccioneCliente.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab_seleccione_seleccioneCliente.setForeground(new java.awt.Color(255, 255, 255));
        lab_seleccione_seleccioneCliente.setText("Seleccione un producto");
        card_seleccione.add(lab_seleccione_seleccioneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, -1, -1));

        lab_seleccione_seleccioneProducto.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab_seleccione_seleccioneProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_seleccione_seleccioneProducto.setText("Seleccione un cliente");
        card_seleccione.add(lab_seleccione_seleccioneProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btn_seleccione_cancelar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_seleccione_cancelar.setText("Cancelar");
        btn_seleccione_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccione_cancelarActionPerformed(evt);
            }
        });
        card_seleccione.add(btn_seleccione_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        btn_seleccione_continuar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_seleccione_continuar.setText("Continuar");
        btn_seleccione_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccione_continuarActionPerformed(evt);
            }
        });
        card_seleccione.add(btn_seleccione_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));
        card_seleccione.add(separador_seleccione, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 750, 10));

        table_venta_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código Cliente", "RUT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_venta_contenedorTablaClientes.setViewportView(table_venta_clientes);

        card_seleccione.add(jScrollPane_venta_contenedorTablaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, -1, 190));

        table_venta_productos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_venta_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Producto", "Nombre Producto", "Precio Producto", "Precio Compra", "Stock", "Ubicación Bodega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_venta_contenedorTablaProducto.setViewportView(table_venta_productos);

        card_seleccione.add(jScrollPane_venta_contenedorTablaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 293, 750, 190));

        lab_productos_background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_productos_background3.setText("jLabel1");
        card_seleccione.add(lab_productos_background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        panel_venta_cartas.add(card_seleccione, "card3");

        card_confirme.setBackground(new java.awt.Color(0, 102, 0));
        card_confirme.setOpaque(false);
        card_confirme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_confirme_resumenVenta.setBackground(new java.awt.Color(255, 255, 255));
        lab_confirme_resumenVenta.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab_confirme_resumenVenta.setForeground(new java.awt.Color(255, 255, 255));
        lab_confirme_resumenVenta.setText("Resumen venta");
        card_confirme.add(lab_confirme_resumenVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtArea_resumen.setEditable(false);
        txtArea_resumen.setBackground(new java.awt.Color(0, 153, 0));
        txtArea_resumen.setColumns(20);
        txtArea_resumen.setRows(5);
        txtArea_resumen.setText("//Acá crear método que obtenga las cosas que fueron seleccionadas en las tablas anteriores\n//Botón Terminar compra reducirá en uno el stock del elemento\n//Añadirá también el producto al cliente(?), para el registro");
        jScrollPane_venta_contenedorTxtArea.setViewportView(txtArea_resumen);

        card_confirme.add(jScrollPane_venta_contenedorTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 750, 520));

        btn_confirme_atras.setText("Atrás");
        btn_confirme_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirme_atrasActionPerformed(evt);
            }
        });
        card_confirme.add(btn_confirme_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, -1, -1));

        btn_confirme_terminarVenta.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_confirme_terminarVenta.setText("Terminar venta");
        btn_confirme_terminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirme_terminarVentaActionPerformed(evt);
            }
        });
        card_confirme.add(btn_confirme_terminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, -1, -1));

        lab_confirme_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_confirme_background.setText("jLabel1");
        card_confirme.add(lab_confirme_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        panel_venta_cartas.add(card_confirme, "card9");

        getContentPane().add(panel_venta_cartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirme_terminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirme_terminarVentaActionPerformed
     this.dispose(); //Hacer que vuelva al menú principal
    }//GEN-LAST:event_btn_confirme_terminarVentaActionPerformed

    private void btn_seleccione_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccione_continuarActionPerformed
        panel_venta_cartas.removeAll();
        panel_venta_cartas.add(card_confirme);
        panel_venta_cartas.repaint();
        panel_venta_cartas.revalidate();
    }//GEN-LAST:event_btn_seleccione_continuarActionPerformed

    private void btn_seleccione_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccione_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_seleccione_cancelarActionPerformed

    private void btn_confirme_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirme_atrasActionPerformed
        panel_venta_cartas.removeAll();
        panel_venta_cartas.add(card_seleccione);
        panel_venta_cartas.repaint();
        panel_venta_cartas.revalidate();
    }//GEN-LAST:event_btn_confirme_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Modulo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_confirme_atras;
    public javax.swing.JButton btn_confirme_terminarVenta;
    public javax.swing.JButton btn_seleccione_cancelar;
    public javax.swing.JButton btn_seleccione_continuar;
    public javax.swing.JPanel card_confirme;
    public javax.swing.JPanel card_seleccione;
    public javax.swing.JScrollPane jScrollPane_venta_contenedorTablaClientes;
    public javax.swing.JScrollPane jScrollPane_venta_contenedorTablaProducto;
    public javax.swing.JScrollPane jScrollPane_venta_contenedorTxtArea;
    public javax.swing.JLabel lab_confirme_background;
    public javax.swing.JLabel lab_confirme_resumenVenta;
    public javax.swing.JLabel lab_productos_background3;
    public javax.swing.JLabel lab_seleccione_seleccioneCliente;
    public javax.swing.JLabel lab_seleccione_seleccioneProducto;
    public javax.swing.JLabel lab_venta_ventaProducto;
    public javax.swing.JPanel panel_venta_cartas;
    public javax.swing.JPanel panel_venta_tituloVenta;
    public javax.swing.JSeparator separador_seleccione;
    public javax.swing.JTable table_venta_clientes;
    public javax.swing.JTable table_venta_productos;
    public javax.swing.JTextArea txtArea_resumen;
    // End of variables declaration//GEN-END:variables
}
