package Vista;

/**
 *
 * @RolandoEscobar
 */
public class Modulo1 extends javax.swing.JFrame {

    /** Creates new form Modulo1 */
    public Modulo1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //línea para habilitar o deshabilitar pestañas
        //jTabbedPane.removeTabAt(0);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mod1_title = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelTab_usuarios = new javax.swing.JPanel();
        lab_usuarios_codUser = new javax.swing.JLabel();
        lab_usuarios_rut = new javax.swing.JLabel();
        lab_usuarios_login = new javax.swing.JLabel();
        lab_usuarios_pass = new javax.swing.JLabel();
        lab_usuarios_pass2 = new javax.swing.JLabel();
        lab_usuarios_estado = new javax.swing.JLabel();
        lab_usuarios_nivelAcceso = new javax.swing.JLabel();
        txt_usuarios_codUser = new javax.swing.JTextField();
        txt_usuarios_rut = new javax.swing.JTextField();
        txt_usuarios_login = new javax.swing.JTextField();
        txt_usuarios_estado = new javax.swing.JTextField();
        pass_usuarios_pass = new javax.swing.JPasswordField();
        pass_usuarios_pass2 = new javax.swing.JPasswordField();
        cbox_usuarios_nivelAcceso = new javax.swing.JComboBox<>();
        jScrollPane_usuarios_contenedorTabla = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();
        jPanel_usuarios_contenedorBotones = new javax.swing.JPanel();
        btn_usuarios_editarRegistro = new javax.swing.JButton();
        btn_usuarios_finEdicion = new javax.swing.JButton();
        btn_usuarios_listarUsuarios = new javax.swing.JButton();
        btn_usuarios_crearNuevoUsuario = new javax.swing.JButton();
        btn_usuarios_eliminarUsuario = new javax.swing.JButton();
        btn_usuarios_limpiar = new javax.swing.JButton();
        jPanelTab_clientes = new javax.swing.JPanel();
        txt_clientes_codUser1 = new javax.swing.JTextField();
        txt_clientes_rut = new javax.swing.JTextField();
        jScrollPane_clientes_contenedorTabla = new javax.swing.JScrollPane();
        table_clientes = new javax.swing.JTable();
        lab_clientes_codCliente = new javax.swing.JLabel();
        lab_clientes_rut = new javax.swing.JLabel();
        jPanel_clientes_contenedorBotones = new javax.swing.JPanel();
        btn_clientes_listarClientes = new javax.swing.JButton();
        btn_clientes_editarRegistro = new javax.swing.JButton();
        btn_clientes_finEdicion = new javax.swing.JButton();
        btn_clientes_aniadirNuevoCliente = new javax.swing.JButton();
        btn_clientes_eliminarCliente = new javax.swing.JButton();
        btn_clientes_limpiar = new javax.swing.JButton();
        jPanelTab_productos = new javax.swing.JPanel();
        lab_productos_codProducto = new javax.swing.JLabel();
        lab_productos_nombreProducto = new javax.swing.JLabel();
        lab_productos_descProducto = new javax.swing.JLabel();
        lab_productos_unidadProducto = new javax.swing.JLabel();
        lab_productos_precioProducto = new javax.swing.JLabel();
        lab_productos_precioCompra = new javax.swing.JLabel();
        lab_productos_stock = new javax.swing.JLabel();
        lab_productos_ubicacionBodega = new javax.swing.JLabel();
        lab_productos_codCategoria = new javax.swing.JLabel();
        txt_productos_codProducto = new javax.swing.JTextField();
        txt_productos_nombreProducto = new javax.swing.JTextField();
        txt_productos_descProducto = new javax.swing.JTextField();
        txt_productos_unidadProducto = new javax.swing.JTextField();
        txt_productos_precioProducto = new javax.swing.JTextField();
        txt_productos_precioCompra = new javax.swing.JTextField();
        txt_productos_stock = new javax.swing.JTextField();
        txt_productos_ubicacionBodega = new javax.swing.JTextField();
        txt_productos_codCategoria = new javax.swing.JTextField();
        jPanel_productos_contenedorBotones = new javax.swing.JPanel();
        btn_productos_listarProductos = new javax.swing.JButton();
        btn_productos_editarRegistro = new javax.swing.JButton();
        btn_productos_finEdicion = new javax.swing.JButton();
        btn_productos_aniadirProducto = new javax.swing.JButton();
        btn_productos_eliminarProducto = new javax.swing.JButton();
        btn_productos_limpiar = new javax.swing.JButton();
        jScrollPane_productos_contenedorTabla = new javax.swing.JScrollPane();
        table_productos = new javax.swing.JTable();
        jPanelTab_categoria = new javax.swing.JPanel();
        lab_categorias_codCategoria = new javax.swing.JLabel();
        lab_categorias_nombreCategoria = new javax.swing.JLabel();
        lab_categorias_desc_Categoria = new javax.swing.JLabel();
        lab_categorias_grupo = new javax.swing.JLabel();
        lab_categorias_borrado = new javax.swing.JLabel();
        txt_categorias_codCategoria = new javax.swing.JTextField();
        txt_categorias_nombreCategoria = new javax.swing.JTextField();
        txt_categorias_descCategoria = new javax.swing.JTextField();
        txt_categorias_grupo = new javax.swing.JTextField();
        txt_categorias_borrado = new javax.swing.JTextField();
        jPanel_categorias_contenedorBotones = new javax.swing.JPanel();
        btn_categorias_listarCategorias = new javax.swing.JButton();
        btn_categorias_editarRegistro = new javax.swing.JButton();
        btn_categorias_finEdicion = new javax.swing.JButton();
        btn_categorias_aniadirCategoria = new javax.swing.JButton();
        btn_categorias_eliminarCategoria = new javax.swing.JButton();
        btn_categorias_limpiar = new javax.swing.JButton();
        jScrollPane_categorias_contenedorTabla = new javax.swing.JScrollPane();
        table_productos1 = new javax.swing.JTable();
        jPanelTab_stock = new javax.swing.JPanel();
        jScrollPane_stock_contenedorTabla = new javax.swing.JScrollPane();
        table_stock = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_stock_listarStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 0));
        setResizable(false);

        mod1_title.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        mod1_title.setText("Seleccione la pestaña correspondiente para agregar, modificar o eliminar registros de la base de datos");

        jTabbedPane.setBackground(new java.awt.Color(0, 51, 0));
        jTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jPanelTab_usuarios.setBackground(new java.awt.Color(0, 51, 0));

        lab_usuarios_codUser.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_codUser.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_codUser.setText("Código Usuario");

        lab_usuarios_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_rut.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_rut.setText("RUT");

        lab_usuarios_login.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_login.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_login.setText("Login");

        lab_usuarios_pass.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_pass.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_pass.setText("Contraseña");

        lab_usuarios_pass2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_pass2.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_pass2.setText("Reingrese contraseña");

        lab_usuarios_estado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_estado.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_estado.setText("Estado");

        lab_usuarios_nivelAcceso.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_nivelAcceso.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_nivelAcceso.setText("Nivel de Acceso");

        txt_usuarios_codUser.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_usuarios_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_usuarios_login.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_usuarios_estado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        pass_usuarios_pass.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pass_usuarios_pass.setText("jPasswordField1");
        pass_usuarios_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_usuarios_passActionPerformed(evt);
            }
        });

        pass_usuarios_pass2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pass_usuarios_pass2.setText("jPasswordField2");

        cbox_usuarios_nivelAcceso.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cbox_usuarios_nivelAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un nivel de acceso", "Administrador", "Supervisor", "Vendedor" }));
        cbox_usuarios_nivelAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_usuarios_nivelAccesoActionPerformed(evt);
            }
        });

        table_usuarios.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Usuario", "RUT", "Login", "Contraseña", "Estado", "Nivel Acceso"
            }
        ));
        jScrollPane_usuarios_contenedorTabla.setViewportView(table_usuarios);

        jPanel_usuarios_contenedorBotones.setBackground(new java.awt.Color(0, 51, 0));
        jPanel_usuarios_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_usuarios_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_editarRegistro.setText("Editar registro");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_usuarios_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_finEdicion.setText("Fin edición");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_usuarios_listarUsuarios.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_listarUsuarios.setText("Listar usuarios");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_listarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_usuarios_crearNuevoUsuario.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_crearNuevoUsuario.setText("Crear nuevo usuario");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_crearNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_usuarios_eliminarUsuario.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_eliminarUsuario.setText("Eliminar usuario");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_eliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_usuarios_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_limpiar.setText("Limpiar todos los campos");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, -1));

        javax.swing.GroupLayout jPanelTab_usuariosLayout = new javax.swing.GroupLayout(jPanelTab_usuarios);
        jPanelTab_usuarios.setLayout(jPanelTab_usuariosLayout);
        jPanelTab_usuariosLayout.setHorizontalGroup(
            jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_usuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_usuarios_contenedorTabla)
                    .addGroup(jPanelTab_usuariosLayout.createSequentialGroup()
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_usuarios_codUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_usuarios_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_usuarios_login, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_usuarios_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_usuarios_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_usuarios_nivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_usuarios_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbox_usuarios_nivelAcceso, 0, 165, Short.MAX_VALUE)
                            .addComponent(txt_usuarios_estado, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(pass_usuarios_pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(pass_usuarios_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_usuarios_login, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_usuarios_rut, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_usuarios_codUser, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_usuarios_contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTab_usuariosLayout.setVerticalGroup(
            jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_usuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTab_usuariosLayout.createSequentialGroup()
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_codUser)
                            .addComponent(txt_usuarios_codUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_rut)
                            .addComponent(txt_usuarios_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_login)
                            .addComponent(txt_usuarios_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_pass)
                            .addComponent(pass_usuarios_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_pass2)
                            .addComponent(pass_usuarios_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_estado)
                            .addComponent(txt_usuarios_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_usuarios_nivelAcceso)
                            .addComponent(cbox_usuarios_nivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel_usuarios_contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85)
                .addComponent(jScrollPane_usuarios_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane.addTab("Usuarios", jPanelTab_usuarios);

        jPanelTab_clientes.setBackground(new java.awt.Color(0, 102, 0));

        txt_clientes_codUser1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_clientes_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        table_clientes.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código Cliente", "RUT"
            }
        ));
        jScrollPane_clientes_contenedorTabla.setViewportView(table_clientes);

        lab_clientes_codCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_clientes_codCliente.setForeground(new java.awt.Color(255, 255, 255));
        lab_clientes_codCliente.setText("Código cliente");

        lab_clientes_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_clientes_rut.setForeground(new java.awt.Color(255, 255, 255));
        lab_clientes_rut.setText("RUT");

        jPanel_clientes_contenedorBotones.setBackground(new java.awt.Color(0, 102, 0));
        jPanel_clientes_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_clientes_listarClientes.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_listarClientes.setText("Listar clientes");
        jPanel_clientes_contenedorBotones.add(btn_clientes_listarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_clientes_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_editarRegistro.setText("Editar registro");
        jPanel_clientes_contenedorBotones.add(btn_clientes_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_clientes_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_finEdicion.setText("Fin edición");
        jPanel_clientes_contenedorBotones.add(btn_clientes_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_clientes_aniadirNuevoCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_aniadirNuevoCliente.setText("Añadir nuevo cliente");
        jPanel_clientes_contenedorBotones.add(btn_clientes_aniadirNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_clientes_eliminarCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_eliminarCliente.setText("Eliminar cliente");
        jPanel_clientes_contenedorBotones.add(btn_clientes_eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_clientes_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_limpiar.setText("Limpiar todos los campos");
        jPanel_clientes_contenedorBotones.add(btn_clientes_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, -1));

        javax.swing.GroupLayout jPanelTab_clientesLayout = new javax.swing.GroupLayout(jPanelTab_clientes);
        jPanelTab_clientes.setLayout(jPanelTab_clientesLayout);
        jPanelTab_clientesLayout.setHorizontalGroup(
            jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_clientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTab_clientesLayout.createSequentialGroup()
                        .addGroup(jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_clientes_codCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_clientes_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_clientes_rut, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_clientes_codUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addComponent(jScrollPane_clientes_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_clientes_contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTab_clientesLayout.setVerticalGroup(
            jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_clientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTab_clientesLayout.createSequentialGroup()
                        .addGroup(jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_clientes_codCliente)
                            .addComponent(txt_clientes_codUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_clientes_rut)
                            .addComponent(txt_clientes_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel_clientes_contenedorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jScrollPane_clientes_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Clientes", jPanelTab_clientes);

        jPanelTab_productos.setBackground(new java.awt.Color(0, 51, 0));

        lab_productos_codProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_codProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_codProducto.setText("Código Producto");

        lab_productos_nombreProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_nombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_nombreProducto.setText("Nombre Producto");

        lab_productos_descProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_descProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_descProducto.setText("Descripción Producto");

        lab_productos_unidadProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_unidadProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_unidadProducto.setText("Unidad Producto");

        lab_productos_precioProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_precioProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_precioProducto.setText("Precio Producto");

        lab_productos_precioCompra.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_precioCompra.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_precioCompra.setText("Precio Compra");

        lab_productos_stock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_stock.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_stock.setText("Stock Producto");

        lab_productos_ubicacionBodega.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_ubicacionBodega.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_ubicacionBodega.setText("Ubicación en Bodega");

        lab_productos_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_codCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_codCategoria.setText("Código Categoría");

        txt_productos_codProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_nombreProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_descProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_unidadProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_precioProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_precioCompra.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_stock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_ubicacionBodega.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_productos_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        jPanel_productos_contenedorBotones.setBackground(new java.awt.Color(0, 51, 0));
        jPanel_productos_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_productos_listarProductos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_listarProductos.setText("Listar produtos");
        jPanel_productos_contenedorBotones.add(btn_productos_listarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_productos_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_editarRegistro.setText("Editar registro");
        jPanel_productos_contenedorBotones.add(btn_productos_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_productos_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_finEdicion.setText("Fin edición");
        jPanel_productos_contenedorBotones.add(btn_productos_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_productos_aniadirProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_aniadirProducto.setText("Añadir producto");
        jPanel_productos_contenedorBotones.add(btn_productos_aniadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_productos_eliminarProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_eliminarProducto.setText("Eliminar producto");
        btn_productos_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productos_eliminarProductoActionPerformed(evt);
            }
        });
        jPanel_productos_contenedorBotones.add(btn_productos_eliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_productos_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_limpiar.setText("Limpiar todos los campos");
        jPanel_productos_contenedorBotones.add(btn_productos_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, -1));

        table_productos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Producto", "Nombre Producto", "Descripción", "Unidad", "Precio Producto", "Precio Compra", "Stock", "Ubicación Bodega", "Código Categoría"
            }
        ));
        jScrollPane_productos_contenedorTabla.setViewportView(table_productos);

        javax.swing.GroupLayout jPanelTab_productosLayout = new javax.swing.GroupLayout(jPanelTab_productos);
        jPanelTab_productos.setLayout(jPanelTab_productosLayout);
        jPanelTab_productosLayout.setHorizontalGroup(
            jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_productosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_productos_contenedorTabla)
                    .addGroup(jPanelTab_productosLayout.createSequentialGroup()
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTab_productosLayout.createSequentialGroup()
                                .addComponent(lab_productos_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(txt_productos_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelTab_productosLayout.createSequentialGroup()
                                    .addComponent(lab_productos_ubicacionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(txt_productos_ubicacionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTab_productosLayout.createSequentialGroup()
                                    .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lab_productos_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_productos_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_productos_descProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_productos_unidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_productos_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_productos_precioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_productos_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(65, 65, 65)
                                    .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_productos_precioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(txt_productos_descProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(txt_productos_nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(txt_productos_codProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(txt_productos_unidadProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(txt_productos_precioProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(txt_productos_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_productos_contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTab_productosLayout.setVerticalGroup(
            jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_productosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTab_productosLayout.createSequentialGroup()
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_codProducto)
                            .addComponent(txt_productos_codProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_nombreProducto)
                            .addComponent(txt_productos_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_descProducto)
                            .addComponent(txt_productos_descProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_unidadProducto)
                            .addComponent(txt_productos_unidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_precioProducto)
                            .addComponent(txt_productos_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_precioCompra)
                            .addComponent(txt_productos_precioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_productos_stock)
                            .addComponent(txt_productos_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel_productos_contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_productos_ubicacionBodega)
                    .addComponent(txt_productos_ubicacionBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTab_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_productos_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_productos_codCategoria))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_productos_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTabbedPane.addTab("Productos", jPanelTab_productos);

        jPanelTab_categoria.setBackground(new java.awt.Color(0, 102, 0));

        lab_categorias_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_codCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_codCategoria.setText("Código Categoría");

        lab_categorias_nombreCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_nombreCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_nombreCategoria.setText("Nombre Categoría");

        lab_categorias_desc_Categoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_desc_Categoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_desc_Categoria.setText("Descripción Categoría");

        lab_categorias_grupo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_grupo.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_grupo.setText("Grupo");

        lab_categorias_borrado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_borrado.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_borrado.setText("Borrado");

        txt_categorias_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_categorias_nombreCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_categorias_descCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_categorias_grupo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        txt_categorias_borrado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        jPanel_categorias_contenedorBotones.setBackground(new java.awt.Color(0, 102, 0));
        jPanel_categorias_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_categorias_listarCategorias.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_listarCategorias.setText("Listar categorías");
        jPanel_categorias_contenedorBotones.add(btn_categorias_listarCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_categorias_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_editarRegistro.setText("Editar registro");
        jPanel_categorias_contenedorBotones.add(btn_categorias_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_categorias_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_finEdicion.setText("Fin edición");
        jPanel_categorias_contenedorBotones.add(btn_categorias_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_categorias_aniadirCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_aniadirCategoria.setText("Añadir categoría");
        jPanel_categorias_contenedorBotones.add(btn_categorias_aniadirCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_categorias_eliminarCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_eliminarCategoria.setText("Eliminar categoría");
        btn_categorias_eliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categorias_eliminarCategoriaActionPerformed(evt);
            }
        });
        jPanel_categorias_contenedorBotones.add(btn_categorias_eliminarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_categorias_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_limpiar.setText("Limpiar todos los campos");
        jPanel_categorias_contenedorBotones.add(btn_categorias_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, -1));

        table_productos1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Código", "Descripción", "Grupo", "Borrado"
            }
        ));
        jScrollPane_categorias_contenedorTabla.setViewportView(table_productos1);

        javax.swing.GroupLayout jPanelTab_categoriaLayout = new javax.swing.GroupLayout(jPanelTab_categoria);
        jPanelTab_categoria.setLayout(jPanelTab_categoriaLayout);
        jPanelTab_categoriaLayout.setHorizontalGroup(
            jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_categoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_categorias_contenedorTabla)
                    .addGroup(jPanelTab_categoriaLayout.createSequentialGroup()
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_categorias_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_categorias_nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_categorias_desc_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_categorias_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab_categorias_borrado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_categorias_descCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_categorias_nombreCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_categorias_grupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_categorias_borrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txt_categorias_codCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_categorias_contenedorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTab_categoriaLayout.setVerticalGroup(
            jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_categoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTab_categoriaLayout.createSequentialGroup()
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_categorias_codCategoria)
                            .addComponent(txt_categorias_codCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_categorias_nombreCategoria)
                            .addComponent(txt_categorias_nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_categorias_desc_Categoria)
                            .addComponent(txt_categorias_descCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_categorias_grupo)
                            .addComponent(txt_categorias_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTab_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_categorias_borrado)
                            .addComponent(txt_categorias_borrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel_categorias_contenedorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jScrollPane_categorias_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Categorías", jPanelTab_categoria);

        jPanelTab_stock.setBackground(new java.awt.Color(0, 51, 0));

        table_stock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Producto", "Nombre Producto", "Descripción Producto", "Unidad", "Precio Producto", "Precio Compra", "Stock Producto", "Fecha Stock"
            }
        ));
        jScrollPane_stock_contenedorTabla.setViewportView(table_stock);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        btn_stock_listarStock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_stock_listarStock.setText("Actualizar stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_stock_listarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_stock_listarStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelTab_stockLayout = new javax.swing.GroupLayout(jPanelTab_stock);
        jPanelTab_stock.setLayout(jPanelTab_stockLayout);
        jPanelTab_stockLayout.setHorizontalGroup(
            jPanelTab_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_stockLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTab_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_stock_contenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                    .addGroup(jPanelTab_stockLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTab_stockLayout.setVerticalGroup(
            jPanelTab_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTab_stockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_stock_contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Stock", jPanelTab_stock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mod1_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mod1_title)
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_usuarios_nivelAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_usuarios_nivelAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_usuarios_nivelAccesoActionPerformed

    private void pass_usuarios_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_usuarios_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_usuarios_passActionPerformed

    private void btn_productos_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productos_eliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_productos_eliminarProductoActionPerformed

    private void btn_categorias_eliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categorias_eliminarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_categorias_eliminarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_categorias_aniadirCategoria;
    public javax.swing.JButton btn_categorias_editarRegistro;
    public javax.swing.JButton btn_categorias_eliminarCategoria;
    public javax.swing.JButton btn_categorias_finEdicion;
    public javax.swing.JButton btn_categorias_limpiar;
    public javax.swing.JButton btn_categorias_listarCategorias;
    public javax.swing.JButton btn_clientes_aniadirNuevoCliente;
    public javax.swing.JButton btn_clientes_editarRegistro;
    public javax.swing.JButton btn_clientes_eliminarCliente;
    public javax.swing.JButton btn_clientes_finEdicion;
    public javax.swing.JButton btn_clientes_limpiar;
    public javax.swing.JButton btn_clientes_listarClientes;
    public javax.swing.JButton btn_productos_aniadirProducto;
    public javax.swing.JButton btn_productos_editarRegistro;
    public javax.swing.JButton btn_productos_eliminarProducto;
    public javax.swing.JButton btn_productos_finEdicion;
    public javax.swing.JButton btn_productos_limpiar;
    public javax.swing.JButton btn_productos_listarProductos;
    public javax.swing.JButton btn_stock_listarStock;
    public javax.swing.JButton btn_usuarios_crearNuevoUsuario;
    public javax.swing.JButton btn_usuarios_editarRegistro;
    public javax.swing.JButton btn_usuarios_eliminarUsuario;
    public javax.swing.JButton btn_usuarios_finEdicion;
    public javax.swing.JButton btn_usuarios_limpiar;
    public javax.swing.JButton btn_usuarios_listarUsuarios;
    public javax.swing.JComboBox<String> cbox_usuarios_nivelAcceso;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelTab_categoria;
    public javax.swing.JPanel jPanelTab_clientes;
    public javax.swing.JPanel jPanelTab_productos;
    public javax.swing.JPanel jPanelTab_stock;
    public javax.swing.JPanel jPanelTab_usuarios;
    public javax.swing.JPanel jPanel_categorias_contenedorBotones;
    public javax.swing.JPanel jPanel_clientes_contenedorBotones;
    public javax.swing.JPanel jPanel_productos_contenedorBotones;
    public javax.swing.JPanel jPanel_usuarios_contenedorBotones;
    public javax.swing.JScrollPane jScrollPane_categorias_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_clientes_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_productos_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_stock_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_usuarios_contenedorTabla;
    public javax.swing.JTabbedPane jTabbedPane;
    public javax.swing.JLabel lab_categorias_borrado;
    public javax.swing.JLabel lab_categorias_codCategoria;
    public javax.swing.JLabel lab_categorias_desc_Categoria;
    public javax.swing.JLabel lab_categorias_grupo;
    public javax.swing.JLabel lab_categorias_nombreCategoria;
    public javax.swing.JLabel lab_clientes_codCliente;
    public javax.swing.JLabel lab_clientes_rut;
    public javax.swing.JLabel lab_productos_codCategoria;
    public javax.swing.JLabel lab_productos_codProducto;
    public javax.swing.JLabel lab_productos_descProducto;
    public javax.swing.JLabel lab_productos_nombreProducto;
    public javax.swing.JLabel lab_productos_precioCompra;
    public javax.swing.JLabel lab_productos_precioProducto;
    public javax.swing.JLabel lab_productos_stock;
    public javax.swing.JLabel lab_productos_ubicacionBodega;
    public javax.swing.JLabel lab_productos_unidadProducto;
    public javax.swing.JLabel lab_usuarios_codUser;
    public javax.swing.JLabel lab_usuarios_estado;
    public javax.swing.JLabel lab_usuarios_login;
    public javax.swing.JLabel lab_usuarios_nivelAcceso;
    public javax.swing.JLabel lab_usuarios_pass;
    public javax.swing.JLabel lab_usuarios_pass2;
    public javax.swing.JLabel lab_usuarios_rut;
    public javax.swing.JLabel mod1_title;
    public javax.swing.JPasswordField pass_usuarios_pass;
    public javax.swing.JPasswordField pass_usuarios_pass2;
    public javax.swing.JTable table_clientes;
    public javax.swing.JTable table_productos;
    public javax.swing.JTable table_productos1;
    public javax.swing.JTable table_stock;
    public javax.swing.JTable table_usuarios;
    public javax.swing.JTextField txt_categorias_borrado;
    public javax.swing.JTextField txt_categorias_codCategoria;
    public javax.swing.JTextField txt_categorias_descCategoria;
    public javax.swing.JTextField txt_categorias_grupo;
    public javax.swing.JTextField txt_categorias_nombreCategoria;
    public javax.swing.JTextField txt_clientes_codUser1;
    public javax.swing.JTextField txt_clientes_rut;
    public javax.swing.JTextField txt_productos_codCategoria;
    public javax.swing.JTextField txt_productos_codProducto;
    public javax.swing.JTextField txt_productos_descProducto;
    public javax.swing.JTextField txt_productos_nombreProducto;
    public javax.swing.JTextField txt_productos_precioCompra;
    public javax.swing.JTextField txt_productos_precioProducto;
    public javax.swing.JTextField txt_productos_stock;
    public javax.swing.JTextField txt_productos_ubicacionBodega;
    public javax.swing.JTextField txt_productos_unidadProducto;
    public javax.swing.JTextField txt_usuarios_codUser;
    public javax.swing.JTextField txt_usuarios_estado;
    public javax.swing.JTextField txt_usuarios_login;
    public javax.swing.JTextField txt_usuarios_rut;
    // End of variables declaration//GEN-END:variables

}
