/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author usuario
 */
public class Modulo2 extends javax.swing.JFrame {

    /**
     * Creates new form Modulo2
     */
    public Modulo2() {
        initComponents();
    }
    
    public void llenarBoleta(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_venta_tituloVenta = new javax.swing.JPanel();
        lab_venta_ventaProducto = new javax.swing.JLabel();
        panel_venta_cartas = new javax.swing.JPanel();
        card_seleccione = new javax.swing.JPanel();
        lab_seleccione_seleccioneCliente = new javax.swing.JLabel();
        lab_seleccione_seleccioneProducto = new javax.swing.JLabel();
        btn_seleccione_cancelar = new javax.swing.JButton();
        btn_seleccione_continuar = new javax.swing.JButton();
        separador_seleccione = new javax.swing.JSeparator();
        jScrollPane_venta_contenedorTablaClientes = new javax.swing.JScrollPane();
        table_venta_clientes = new javax.swing.JTable();
        jScrollPane_venta_contenedorTablaProducto = new javax.swing.JScrollPane();
        table_venta_productos = new javax.swing.JTable();
        card_confirme = new javax.swing.JPanel();
        lab_confirme_resumenVenta = new javax.swing.JLabel();
        btn_confirme_terminarVenta = new javax.swing.JButton();
        jScrollPane_venta_contenedorTxtArea = new javax.swing.JScrollPane();
        txtArea_resumen = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_venta_tituloVenta.setBackground(new java.awt.Color(0, 102, 0));

        lab_venta_ventaProducto.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        lab_venta_ventaProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_venta_ventaProducto.setText("Venta de producto");

        javax.swing.GroupLayout panel_venta_tituloVentaLayout = new javax.swing.GroupLayout(panel_venta_tituloVenta);
        panel_venta_tituloVenta.setLayout(panel_venta_tituloVentaLayout);
        panel_venta_tituloVentaLayout.setHorizontalGroup(
            panel_venta_tituloVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_venta_tituloVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_venta_ventaProducto)
                .addGap(802, 802, 802))
        );
        panel_venta_tituloVentaLayout.setVerticalGroup(
            panel_venta_tituloVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_venta_tituloVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_venta_ventaProducto)
                .addGap(10, 10, 10))
        );

        getContentPane().add(panel_venta_tituloVenta, java.awt.BorderLayout.PAGE_START);

        panel_venta_cartas.setBackground(new java.awt.Color(0, 102, 0));
        panel_venta_cartas.setLayout(new java.awt.CardLayout());

        card_seleccione.setBackground(new java.awt.Color(0, 102, 0));

        lab_seleccione_seleccioneCliente.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab_seleccione_seleccioneCliente.setForeground(new java.awt.Color(255, 255, 255));
        lab_seleccione_seleccioneCliente.setText("Seleccione un producto");

        lab_seleccione_seleccioneProducto.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab_seleccione_seleccioneProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_seleccione_seleccioneProducto.setText("Seleccione un cliente");

        btn_seleccione_cancelar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_seleccione_cancelar.setText("Cancelar");
        btn_seleccione_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccione_cancelarActionPerformed(evt);
            }
        });

        btn_seleccione_continuar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_seleccione_continuar.setText("Continuar");
        btn_seleccione_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccione_continuarActionPerformed(evt);
            }
        });

        table_venta_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código Cliente", "RUT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_venta_contenedorTablaClientes.setViewportView(table_venta_clientes);

        table_venta_productos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_venta_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Producto", "Nombre Producto", "Precio Producto", "Precio Compra", "Stock", "Ubicación Bodega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_venta_contenedorTablaProducto.setViewportView(table_venta_productos);

        javax.swing.GroupLayout card_seleccioneLayout = new javax.swing.GroupLayout(card_seleccione);
        card_seleccione.setLayout(card_seleccioneLayout);
        card_seleccioneLayout.setHorizontalGroup(
            card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_seleccioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(card_seleccioneLayout.createSequentialGroup()
                            .addGroup(card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane_venta_contenedorTablaProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(separador_seleccione, javax.swing.GroupLayout.Alignment.LEADING))
                            .addContainerGap())
                        .addGroup(card_seleccioneLayout.createSequentialGroup()
                            .addGroup(card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane_venta_contenedorTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lab_seleccione_seleccioneProducto)
                                .addComponent(lab_seleccione_seleccioneCliente))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_seleccioneLayout.createSequentialGroup()
                        .addComponent(btn_seleccione_continuar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_seleccione_cancelar)
                        .addContainerGap())))
        );
        card_seleccioneLayout.setVerticalGroup(
            card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_seleccioneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_seleccione_seleccioneProducto)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane_venta_contenedorTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador_seleccione, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lab_seleccione_seleccioneCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_venta_contenedorTablaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(card_seleccioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_seleccione_cancelar)
                    .addComponent(btn_seleccione_continuar))
                .addGap(100, 100, 100))
        );

        panel_venta_cartas.add(card_seleccione, "card3");

        card_confirme.setBackground(new java.awt.Color(0, 102, 0));

        lab_confirme_resumenVenta.setBackground(new java.awt.Color(255, 255, 255));
        lab_confirme_resumenVenta.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lab_confirme_resumenVenta.setForeground(new java.awt.Color(255, 255, 255));
        lab_confirme_resumenVenta.setText("Resumen venta");

        btn_confirme_terminarVenta.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_confirme_terminarVenta.setText("Terminar venta");
        btn_confirme_terminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirme_terminarVentaActionPerformed(evt);
            }
        });

        txtArea_resumen.setEditable(false);
        txtArea_resumen.setBackground(new java.awt.Color(0, 153, 0));
        txtArea_resumen.setColumns(20);
        txtArea_resumen.setRows(5);
        txtArea_resumen.setText("//Acá crear método que obtenga las cosas que fueron seleccionadas en las tablas anteriores\n//Botón Terminar compra reducirá en uno el stock del elemento\n//Añadirá también el producto al cliente(?), para el registro");
        jScrollPane_venta_contenedorTxtArea.setViewportView(txtArea_resumen);

        jButton1.setText("Atrás");

        javax.swing.GroupLayout card_confirmeLayout = new javax.swing.GroupLayout(card_confirme);
        card_confirme.setLayout(card_confirmeLayout);
        card_confirmeLayout.setHorizontalGroup(
            card_confirmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_confirmeLayout.createSequentialGroup()
                .addGroup(card_confirmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_confirmeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_confirme_terminarVenta))
                    .addGroup(card_confirmeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lab_confirme_resumenVenta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(card_confirmeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane_venta_contenedorTxtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)))
                .addContainerGap())
        );
        card_confirmeLayout.setVerticalGroup(
            card_confirmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_confirmeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_confirme_resumenVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_venta_contenedorTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(card_confirmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirme_terminarVenta)
                    .addComponent(jButton1))
                .addGap(69, 69, 69))
        );

        panel_venta_cartas.add(card_confirme, "card9");

        getContentPane().add(panel_venta_cartas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirme_terminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirme_terminarVentaActionPerformed
     this.dispose(); //Hacer que vuelva al menú principal
    }//GEN-LAST:event_btn_confirme_terminarVentaActionPerformed

    private void btn_seleccione_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccione_continuarActionPerformed
        panel_venta_cartas.removeAll();
        panel_venta_cartas.add(card_confirme);
        panel_venta_cartas.repaint();
        panel_venta_cartas.revalidate();
    }//GEN-LAST:event_btn_seleccione_continuarActionPerformed

    private void btn_seleccione_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccione_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_seleccione_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Modulo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_confirme_terminarVenta;
    public javax.swing.JButton btn_seleccione_cancelar;
    public javax.swing.JButton btn_seleccione_continuar;
    public javax.swing.JPanel card_confirme;
    public javax.swing.JPanel card_seleccione;
    private javax.swing.JButton jButton1;
    public javax.swing.JScrollPane jScrollPane_venta_contenedorTablaClientes;
    public javax.swing.JScrollPane jScrollPane_venta_contenedorTablaProducto;
    public javax.swing.JScrollPane jScrollPane_venta_contenedorTxtArea;
    public javax.swing.JLabel lab_confirme_resumenVenta;
    public javax.swing.JLabel lab_seleccione_seleccioneCliente;
    public javax.swing.JLabel lab_seleccione_seleccioneProducto;
    public javax.swing.JLabel lab_venta_ventaProducto;
    public javax.swing.JPanel panel_venta_cartas;
    public javax.swing.JPanel panel_venta_tituloVenta;
    public javax.swing.JSeparator separador_seleccione;
    public javax.swing.JTable table_venta_clientes;
    public javax.swing.JTable table_venta_productos;
    public javax.swing.JTextArea txtArea_resumen;
    // End of variables declaration//GEN-END:variables
}
