/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author PC
 */
public class Modulo4 extends javax.swing.JFrame {

    /**
     * Creates new form Modulo4
     */
    public Modulo4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        box_modulo4_cliente = new javax.swing.JComboBox<>();
        cal_modulo4_desde = new com.toedter.calendar.JDateChooser();
        cal_modulo4_hasta = new com.toedter.calendar.JDateChooser();
        box_modulo4_categoria = new javax.swing.JComboBox<>();
        box_modulo4_producto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_modulo4_productoCantidadMonto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lab_gestionClientes_background3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        box_modulo4_cliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        box_modulo4_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente 1", "Cliente 2", "Cliente 3", "Cliente 4" }));
        getContentPane().add(box_modulo4_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));
        getContentPane().add(cal_modulo4_desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));
        getContentPane().add(cal_modulo4_hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 110, -1));

        box_modulo4_categoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        box_modulo4_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semillas", "Bongs", "Sustratos", "Art. Indoor" }));
        getContentPane().add(box_modulo4_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 83, -1));

        box_modulo4_producto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        box_modulo4_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(box_modulo4_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 93, -1));

        tab_modulo4_productoCantidadMonto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        tab_modulo4_productoCantidadMonto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Monto"
            }
        ));
        tab_modulo4_productoCantidadMonto.setToolTipText("");
        tab_modulo4_productoCantidadMonto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_modulo4_productoCantidadMonto.setOpaque(false);
        jScrollPane2.setViewportView(tab_modulo4_productoCantidadMonto);
        if (tab_modulo4_productoCantidadMonto.getColumnModel().getColumnCount() > 0) {
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(0).setMinWidth(150);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(0).setPreferredWidth(150);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(0).setMaxWidth(150);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(1).setMinWidth(80);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(1).setPreferredWidth(80);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(1).setMaxWidth(80);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(2).setMinWidth(80);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(2).setPreferredWidth(80);
            tab_modulo4_productoCantidadMonto.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 193, 318, 96));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Periodo a Revisar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desde");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hasta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Categoria");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Producto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        lab_gestionClientes_background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_gestionClientes_background3.setText("jLabel1");
        getContentPane().add(lab_gestionClientes_background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> box_modulo4_categoria;
    public javax.swing.JComboBox<String> box_modulo4_cliente;
    public javax.swing.JComboBox<String> box_modulo4_producto;
    public com.toedter.calendar.JDateChooser cal_modulo4_desde;
    public com.toedter.calendar.JDateChooser cal_modulo4_hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lab_gestionClientes_background3;
    public javax.swing.JTable tab_modulo4_productoCantidadMonto;
    // End of variables declaration//GEN-END:variables
}
