package Vista;

/**
 *
 * @RolandoEscobar
 */
public class Modulo1 extends javax.swing.JFrame {

    /** Creates new form Modulo1 */
    public Modulo1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        //línea para habilitar o deshabilitar pestañas
        //jTabbedPane.removeTabAt(0);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mod1_title = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelTab_usuarios = new javax.swing.JPanel();
        lab_usuarios_codUser = new javax.swing.JLabel();
        lab_usuarios_rut = new javax.swing.JLabel();
        lab_usuarios_login = new javax.swing.JLabel();
        lab_usuarios_pass = new javax.swing.JLabel();
        lab_usuarios_nivelAcceso = new javax.swing.JLabel();
        txt_usuarios_codUser = new javax.swing.JTextField();
        txt_usuarios_rut = new javax.swing.JTextField();
        txt_usuarios_login = new javax.swing.JTextField();
        pass_usuarios_pass = new javax.swing.JPasswordField();
        cbox_usuarios_nivelAcceso = new javax.swing.JComboBox<>();
        jScrollPane_usuarios_contenedorTabla = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();
        jPanel_usuarios_contenedorBotones = new javax.swing.JPanel();
        btn_usuarios_editarRegistro = new javax.swing.JButton();
        btn_usuarios_finEdicion = new javax.swing.JButton();
        btn_usuarios_listarUsuarios = new javax.swing.JButton();
        btn_usuarios_crearNuevoUsuario = new javax.swing.JButton();
        btn_usuarios_eliminarUsuario = new javax.swing.JButton();
        btn_usuarios_limpiar = new javax.swing.JButton();
        lab_usuarios_background = new javax.swing.JLabel();
        jPanelTab_clientes = new javax.swing.JPanel();
        txt_clientes_codUser1 = new javax.swing.JTextField();
        txt_clientes_rut = new javax.swing.JTextField();
        jScrollPane_clientes_contenedorTabla = new javax.swing.JScrollPane();
        table_clientes = new javax.swing.JTable();
        lab_clientes_codCliente = new javax.swing.JLabel();
        lab_clientes_rut = new javax.swing.JLabel();
        jPanel_clientes_contenedorBotones = new javax.swing.JPanel();
        btn_clientes_listarClientes = new javax.swing.JButton();
        btn_clientes_editarRegistro = new javax.swing.JButton();
        btn_clientes_finEdicion = new javax.swing.JButton();
        btn_clientes_aniadirNuevoCliente = new javax.swing.JButton();
        btn_clientes_eliminarCliente = new javax.swing.JButton();
        btn_clientes_limpiar = new javax.swing.JButton();
        lab_clientes_background1 = new javax.swing.JLabel();
        jPanelTab_productos = new javax.swing.JPanel();
        lab_productos_codProducto = new javax.swing.JLabel();
        lab_productos_nombreProducto = new javax.swing.JLabel();
        lab_productos_descProducto = new javax.swing.JLabel();
        lab_productos_unidadProducto = new javax.swing.JLabel();
        lab_productos_precioProducto = new javax.swing.JLabel();
        lab_productos_precioCompra = new javax.swing.JLabel();
        lab_productos_stock = new javax.swing.JLabel();
        lab_productos_ubicacionBodega = new javax.swing.JLabel();
        lab_productos_codCategoria = new javax.swing.JLabel();
        txt_productos_codProducto = new javax.swing.JTextField();
        txt_productos_nombreProducto = new javax.swing.JTextField();
        txt_productos_descProducto = new javax.swing.JTextField();
        txt_productos_unidadProducto = new javax.swing.JTextField();
        txt_productos_precioProducto = new javax.swing.JTextField();
        txt_productos_precioCompra = new javax.swing.JTextField();
        txt_productos_stock = new javax.swing.JTextField();
        txt_productos_ubicacionBodega = new javax.swing.JTextField();
        txt_productos_codCategoria = new javax.swing.JTextField();
        jPanel_productos_contenedorBotones = new javax.swing.JPanel();
        btn_productos_listarProductos = new javax.swing.JButton();
        btn_productos_editarRegistro = new javax.swing.JButton();
        btn_productos_finEdicion = new javax.swing.JButton();
        btn_productos_aniadirProducto = new javax.swing.JButton();
        btn_productos_eliminarProducto = new javax.swing.JButton();
        btn_productos_limpiar = new javax.swing.JButton();
        jScrollPane_productos_contenedorTabla = new javax.swing.JScrollPane();
        table_productos = new javax.swing.JTable();
        lab_productos_background2 = new javax.swing.JLabel();
        jPanelTab_categoria = new javax.swing.JPanel();
        lab_categorias_nombreCategoria = new javax.swing.JLabel();
        lab_categorias_codCategoria = new javax.swing.JLabel();
        lab_categorias_desc_Categoria = new javax.swing.JLabel();
        lab_categorias_grupo = new javax.swing.JLabel();
        lab_categorias_borrado = new javax.swing.JLabel();
        txt_categorias_nombreCategoria = new javax.swing.JTextField();
        txt_categorias_codCategoria = new javax.swing.JTextField();
        txt_categorias_descCategoria = new javax.swing.JTextField();
        txt_categorias_grupo = new javax.swing.JTextField();
        txt_categorias_borrado = new javax.swing.JTextField();
        jPanel_categorias_contenedorBotones = new javax.swing.JPanel();
        btn_categorias_listarCategorias = new javax.swing.JButton();
        btn_categorias_editarRegistro = new javax.swing.JButton();
        btn_categorias_finEdicion = new javax.swing.JButton();
        btn_categorias_aniadirCategoria = new javax.swing.JButton();
        btn_categorias_eliminarCategoria = new javax.swing.JButton();
        btn_categorias_limpiar = new javax.swing.JButton();
        jScrollPane_categorias_contenedorTabla = new javax.swing.JScrollPane();
        table_productos1 = new javax.swing.JTable();
        lab_categorias_background3 = new javax.swing.JLabel();
        jPanelTab_stock = new javax.swing.JPanel();
        jScrollPane_stock_contenedorTabla = new javax.swing.JScrollPane();
        table_stock = new javax.swing.JTable();
        btn_stock_listarStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lab_stock_currentStock = new javax.swing.JLabel();
        btn_stock_editStock = new javax.swing.JButton();
        txt_stock_newStock = new javax.swing.JTextField();
        btn_stock_finCambio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lab_productos_background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 0));
        setResizable(false);

        mod1_title.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        mod1_title.setText("Seleccione la pestaña correspondiente para agregar, modificar o eliminar registros de la base de datos");

        jTabbedPane.setBackground(new java.awt.Color(0, 51, 0));
        jTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jPanelTab_usuarios.setBackground(new java.awt.Color(0, 51, 0));
        jPanelTab_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_usuarios_codUser.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_codUser.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_codUser.setText("Código Usuario");
        jPanelTab_usuarios.add(lab_usuarios_codUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 130, -1));

        lab_usuarios_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_rut.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_rut.setText("RUT");
        jPanelTab_usuarios.add(lab_usuarios_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 130, -1));

        lab_usuarios_login.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_login.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_login.setText("Login");
        jPanelTab_usuarios.add(lab_usuarios_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, 130, -1));

        lab_usuarios_pass.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_pass.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_pass.setText("Contraseña");
        jPanelTab_usuarios.add(lab_usuarios_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        lab_usuarios_nivelAcceso.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_usuarios_nivelAcceso.setForeground(new java.awt.Color(255, 255, 255));
        lab_usuarios_nivelAcceso.setText("Nivel de Acceso");
        jPanelTab_usuarios.add(lab_usuarios_nivelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        txt_usuarios_codUser.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_usuarios.add(txt_usuarios_codUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 20, 165, -1));

        txt_usuarios_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_usuarios.add(txt_usuarios_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 59, 165, -1));

        txt_usuarios_login.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_usuarios.add(txt_usuarios_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 98, 165, -1));

        pass_usuarios_pass.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pass_usuarios_pass.setText("jPasswordField1");
        pass_usuarios_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_usuarios_passActionPerformed(evt);
            }
        });
        jPanelTab_usuarios.add(pass_usuarios_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 137, 165, -1));

        cbox_usuarios_nivelAcceso.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cbox_usuarios_nivelAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un nivel de acceso", "Administrador", "Supervisor", "Vendedor" }));
        cbox_usuarios_nivelAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_usuarios_nivelAccesoActionPerformed(evt);
            }
        });
        jPanelTab_usuarios.add(cbox_usuarios_nivelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, -1));

        table_usuarios.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código Usuario", "RUT", "Login", "Contraseña", "Estado", "Nivel Acceso"
            }
        ));
        jScrollPane_usuarios_contenedorTabla.setViewportView(table_usuarios);

        jPanelTab_usuarios.add(jScrollPane_usuarios_contenedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 975, 187));

        jPanel_usuarios_contenedorBotones.setBackground(new java.awt.Color(0, 51, 0));
        jPanel_usuarios_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_usuarios_contenedorBotones.setOpaque(false);

        btn_usuarios_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_editarRegistro.setText("Editar registro");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_usuarios_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_finEdicion.setText("Fin edición");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_usuarios_listarUsuarios.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_listarUsuarios.setText("Listar usuarios");
        btn_usuarios_listarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarios_listarUsuariosActionPerformed(evt);
            }
        });
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_listarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_usuarios_crearNuevoUsuario.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_crearNuevoUsuario.setText("Crear nuevo usuario");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_crearNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 230, -1));

        btn_usuarios_eliminarUsuario.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_eliminarUsuario.setText("Eliminar usuario (desactivar)");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_eliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, -1));

        btn_usuarios_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_usuarios_limpiar.setText("Limpiar todos los campos");
        jPanel_usuarios_contenedorBotones.add(btn_usuarios_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 230, -1));

        jPanelTab_usuarios.add(jPanel_usuarios_contenedorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 20, 597, 255));

        lab_usuarios_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_usuarios_background.setText("jLabel1");
        jPanelTab_usuarios.add(lab_usuarios_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        jTabbedPane.addTab("Usuarios", jPanelTab_usuarios);

        jPanelTab_clientes.setBackground(new java.awt.Color(0, 102, 0));
        jPanelTab_clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_clientes_codUser1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_clientes.add(txt_clientes_codUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 20, 165, -1));

        txt_clientes_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_clientes.add(txt_clientes_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 59, 165, -1));

        table_clientes.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código Cliente", "RUT"
            }
        ));
        jScrollPane_clientes_contenedorTabla.setViewportView(table_clientes);

        jPanelTab_clientes.add(jScrollPane_clientes_contenedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 300, 187));

        lab_clientes_codCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_clientes_codCliente.setForeground(new java.awt.Color(255, 255, 255));
        lab_clientes_codCliente.setText("Código cliente");
        jPanelTab_clientes.add(lab_clientes_codCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 130, -1));

        lab_clientes_rut.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_clientes_rut.setForeground(new java.awt.Color(255, 255, 255));
        lab_clientes_rut.setText("RUT");
        jPanelTab_clientes.add(lab_clientes_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 130, -1));

        jPanel_clientes_contenedorBotones.setBackground(new java.awt.Color(0, 102, 0));
        jPanel_clientes_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_clientes_contenedorBotones.setOpaque(false);

        btn_clientes_listarClientes.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_listarClientes.setText("Listar clientes");
        jPanel_clientes_contenedorBotones.add(btn_clientes_listarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_clientes_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_editarRegistro.setText("Editar registro");
        jPanel_clientes_contenedorBotones.add(btn_clientes_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_clientes_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_finEdicion.setText("Fin edición");
        jPanel_clientes_contenedorBotones.add(btn_clientes_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_clientes_aniadirNuevoCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_aniadirNuevoCliente.setText("Añadir nuevo cliente");
        jPanel_clientes_contenedorBotones.add(btn_clientes_aniadirNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_clientes_eliminarCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_eliminarCliente.setText("Eliminar cliente");
        jPanel_clientes_contenedorBotones.add(btn_clientes_eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_clientes_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_clientes_limpiar.setText("Limpiar todos los campos");
        jPanel_clientes_contenedorBotones.add(btn_clientes_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 230, -1));

        jPanelTab_clientes.add(jPanel_clientes_contenedorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 20, 600, 248));

        lab_clientes_background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_clientes_background1.setText("jLabel1");
        jPanelTab_clientes.add(lab_clientes_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        jTabbedPane.addTab("Clientes", jPanelTab_clientes);

        jPanelTab_productos.setBackground(new java.awt.Color(0, 51, 0));
        jPanelTab_productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_productos_codProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_codProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_codProducto.setText("Código Producto");
        jPanelTab_productos.add(lab_productos_codProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 130, -1));

        lab_productos_nombreProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_nombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_nombreProducto.setText("Nombre Producto");
        jPanelTab_productos.add(lab_productos_nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 130, -1));

        lab_productos_descProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_descProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_descProducto.setText("Descripción Producto");
        jPanelTab_productos.add(lab_productos_descProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, 130, -1));

        lab_productos_unidadProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_unidadProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_unidadProducto.setText("Unidad Producto");
        jPanelTab_productos.add(lab_productos_unidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        lab_productos_precioProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_precioProducto.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_precioProducto.setText("Precio Producto");
        jPanelTab_productos.add(lab_productos_precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 179, 130, -1));

        lab_productos_precioCompra.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_precioCompra.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_precioCompra.setText("Precio Compra");
        jPanelTab_productos.add(lab_productos_precioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, 130, -1));

        lab_productos_stock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_stock.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_stock.setText("Stock Producto");
        jPanelTab_productos.add(lab_productos_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 257, 130, -1));

        lab_productos_ubicacionBodega.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_ubicacionBodega.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_ubicacionBodega.setText("Ubicación en Bodega");
        jPanelTab_productos.add(lab_productos_ubicacionBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 130, -1));

        lab_productos_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_productos_codCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_productos_codCategoria.setText("Código Categoría");
        jPanelTab_productos.add(lab_productos_codCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 335, 130, -1));

        txt_productos_codProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_codProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 20, 165, -1));

        txt_productos_nombreProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 59, 165, -1));

        txt_productos_descProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_descProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 98, 165, -1));

        txt_productos_unidadProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_unidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 137, 165, -1));

        txt_productos_precioProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 176, 165, -1));

        txt_productos_precioCompra.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_precioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 215, 165, -1));

        txt_productos_stock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 254, 165, -1));

        txt_productos_ubicacionBodega.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_ubicacionBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 293, 165, -1));

        txt_productos_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_productos.add(txt_productos_codCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 332, 165, -1));

        jPanel_productos_contenedorBotones.setBackground(new java.awt.Color(0, 51, 0));
        jPanel_productos_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_productos_contenedorBotones.setOpaque(false);

        btn_productos_listarProductos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_listarProductos.setText("Listar produtos");
        jPanel_productos_contenedorBotones.add(btn_productos_listarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_productos_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_editarRegistro.setText("Editar registro");
        jPanel_productos_contenedorBotones.add(btn_productos_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_productos_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_finEdicion.setText("Fin edición");
        jPanel_productos_contenedorBotones.add(btn_productos_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_productos_aniadirProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_aniadirProducto.setText("Añadir producto");
        jPanel_productos_contenedorBotones.add(btn_productos_aniadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_productos_eliminarProducto.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_eliminarProducto.setText("Eliminar producto");
        btn_productos_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productos_eliminarProductoActionPerformed(evt);
            }
        });
        jPanel_productos_contenedorBotones.add(btn_productos_eliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_productos_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_productos_limpiar.setText("Limpiar todos los campos");
        jPanel_productos_contenedorBotones.add(btn_productos_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 230, -1));

        jPanelTab_productos.add(jPanel_productos_contenedorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 20, 594, 255));

        table_productos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Producto", "Nombre Producto", "Descripción", "Unidad", "Precio Producto", "Precio Compra", "Stock", "Ubicación Bodega", "Código Categoría"
            }
        ));
        jScrollPane_productos_contenedorTabla.setViewportView(table_productos);

        jPanelTab_productos.add(jScrollPane_productos_contenedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 371, 972, 187));

        lab_productos_background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_productos_background2.setText("jLabel1");
        jPanelTab_productos.add(lab_productos_background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        jTabbedPane.addTab("Productos", jPanelTab_productos);

        jPanelTab_categoria.setBackground(new java.awt.Color(0, 102, 0));
        jPanelTab_categoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_categorias_nombreCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_nombreCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_nombreCategoria.setText("Nombre Categoría");
        jPanelTab_categoria.add(lab_categorias_nombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 130, -1));

        lab_categorias_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_codCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_codCategoria.setText("Código Categoría");
        jPanelTab_categoria.add(lab_categorias_codCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, 130, -1));

        lab_categorias_desc_Categoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_desc_Categoria.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_desc_Categoria.setText("Descripción Categoría");
        jPanelTab_categoria.add(lab_categorias_desc_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 101, 130, -1));

        lab_categorias_grupo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_grupo.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_grupo.setText("Grupo");
        jPanelTab_categoria.add(lab_categorias_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        lab_categorias_borrado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_categorias_borrado.setForeground(new java.awt.Color(255, 255, 255));
        lab_categorias_borrado.setText("Borrado");
        jPanelTab_categoria.add(lab_categorias_borrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 179, 130, -1));

        txt_categorias_nombreCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_categoria.add(txt_categorias_nombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 20, 165, -1));

        txt_categorias_codCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_categoria.add(txt_categorias_codCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 59, 165, -1));

        txt_categorias_descCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_categoria.add(txt_categorias_descCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 98, 165, -1));

        txt_categorias_grupo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_categoria.add(txt_categorias_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 137, 165, -1));

        txt_categorias_borrado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jPanelTab_categoria.add(txt_categorias_borrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 176, 165, -1));

        jPanel_categorias_contenedorBotones.setBackground(new java.awt.Color(0, 102, 0));
        jPanel_categorias_contenedorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_categorias_contenedorBotones.setOpaque(false);

        btn_categorias_listarCategorias.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_listarCategorias.setText("Listar categorías");
        jPanel_categorias_contenedorBotones.add(btn_categorias_listarCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 150, -1));

        btn_categorias_editarRegistro.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_editarRegistro.setText("Editar registro");
        jPanel_categorias_contenedorBotones.add(btn_categorias_editarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        btn_categorias_finEdicion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_finEdicion.setText("Fin edición");
        jPanel_categorias_contenedorBotones.add(btn_categorias_finEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        btn_categorias_aniadirCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_aniadirCategoria.setText("Añadir categoría");
        jPanel_categorias_contenedorBotones.add(btn_categorias_aniadirCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        btn_categorias_eliminarCategoria.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_eliminarCategoria.setText("Eliminar categoría");
        btn_categorias_eliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categorias_eliminarCategoriaActionPerformed(evt);
            }
        });
        jPanel_categorias_contenedorBotones.add(btn_categorias_eliminarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, -1));

        btn_categorias_limpiar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_categorias_limpiar.setText("Limpiar todos los campos");
        jPanel_categorias_contenedorBotones.add(btn_categorias_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 230, -1));

        jPanelTab_categoria.add(jPanel_categorias_contenedorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 20, 594, 248));

        table_productos1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Código", "Descripción", "Grupo", "Borrado"
            }
        ));
        jScrollPane_categorias_contenedorTabla.setViewportView(table_productos1);

        jPanelTab_categoria.add(jScrollPane_categorias_contenedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 353, 972, 187));

        lab_categorias_background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_categorias_background3.setText("jLabel1");
        jPanelTab_categoria.add(lab_categorias_background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        jTabbedPane.addTab("Categorías", jPanelTab_categoria);

        jPanelTab_stock.setBackground(new java.awt.Color(0, 51, 0));
        jPanelTab_stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_stock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        table_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Producto", "Nombre Producto", "Descripción Producto", "Unidad", "Precio Producto", "Precio Compra", "Stock Producto", "Fecha Stock"
            }
        ));
        jScrollPane_stock_contenedorTabla.setViewportView(table_stock);

        jPanelTab_stock.setOpaque(false);

        jPanelTab_stock.add(jScrollPane_stock_contenedorTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 972, 350));

        btn_stock_listarStock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_stock_listarStock.setText("Actualizar tabla de stock");
        jPanelTab_stock.add(btn_stock_listarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Stock del producto seleccionado");
        jPanelTab_stock.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        lab_stock_currentStock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lab_stock_currentStock.setForeground(new java.awt.Color(204, 204, 204));
        lab_stock_currentStock.setText(" ");
        jPanelTab_stock.add(lab_stock_currentStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 20, -1));

        btn_stock_editStock.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_stock_editStock.setText("Cambiar stock");
        jPanelTab_stock.add(btn_stock_editStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, -1));

        txt_stock_newStock.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTab_stock.add(txt_stock_newStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, 30));

        btn_stock_finCambio.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_stock_finCambio.setText("OK");
        jPanelTab_stock.add(btn_stock_finCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nuevo Stock");
        jPanelTab_stock.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        lab_productos_background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lab_productos_background3.setText("jLabel1");
        jPanelTab_stock.add(lab_productos_background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1000, 640));

        jTabbedPane.addTab("Stock", jPanelTab_stock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mod1_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mod1_title)
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_usuarios_nivelAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_usuarios_nivelAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_usuarios_nivelAccesoActionPerformed

    private void pass_usuarios_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_usuarios_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_usuarios_passActionPerformed

    private void btn_productos_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productos_eliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_productos_eliminarProductoActionPerformed

    private void btn_categorias_eliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categorias_eliminarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_categorias_eliminarCategoriaActionPerformed

    private void btn_usuarios_listarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarios_listarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuarios_listarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_categorias_aniadirCategoria;
    public javax.swing.JButton btn_categorias_editarRegistro;
    public javax.swing.JButton btn_categorias_eliminarCategoria;
    public javax.swing.JButton btn_categorias_finEdicion;
    public javax.swing.JButton btn_categorias_limpiar;
    public javax.swing.JButton btn_categorias_listarCategorias;
    public javax.swing.JButton btn_clientes_aniadirNuevoCliente;
    public javax.swing.JButton btn_clientes_editarRegistro;
    public javax.swing.JButton btn_clientes_eliminarCliente;
    public javax.swing.JButton btn_clientes_finEdicion;
    public javax.swing.JButton btn_clientes_limpiar;
    public javax.swing.JButton btn_clientes_listarClientes;
    public javax.swing.JButton btn_productos_aniadirProducto;
    public javax.swing.JButton btn_productos_editarRegistro;
    public javax.swing.JButton btn_productos_eliminarProducto;
    public javax.swing.JButton btn_productos_finEdicion;
    public javax.swing.JButton btn_productos_limpiar;
    public javax.swing.JButton btn_productos_listarProductos;
    public javax.swing.JButton btn_stock_editStock;
    public javax.swing.JButton btn_stock_finCambio;
    public javax.swing.JButton btn_stock_listarStock;
    public javax.swing.JButton btn_usuarios_crearNuevoUsuario;
    public javax.swing.JButton btn_usuarios_editarRegistro;
    public javax.swing.JButton btn_usuarios_eliminarUsuario;
    public javax.swing.JButton btn_usuarios_finEdicion;
    public javax.swing.JButton btn_usuarios_limpiar;
    public javax.swing.JButton btn_usuarios_listarUsuarios;
    public javax.swing.JComboBox<String> cbox_usuarios_nivelAcceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanelTab_categoria;
    public javax.swing.JPanel jPanelTab_clientes;
    public javax.swing.JPanel jPanelTab_productos;
    public javax.swing.JPanel jPanelTab_stock;
    public javax.swing.JPanel jPanelTab_usuarios;
    public javax.swing.JPanel jPanel_categorias_contenedorBotones;
    public javax.swing.JPanel jPanel_clientes_contenedorBotones;
    public javax.swing.JPanel jPanel_productos_contenedorBotones;
    public javax.swing.JPanel jPanel_usuarios_contenedorBotones;
    public javax.swing.JScrollPane jScrollPane_categorias_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_clientes_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_productos_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_stock_contenedorTabla;
    public javax.swing.JScrollPane jScrollPane_usuarios_contenedorTabla;
    public javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lab_categorias_background3;
    public javax.swing.JLabel lab_categorias_borrado;
    public javax.swing.JLabel lab_categorias_codCategoria;
    public javax.swing.JLabel lab_categorias_desc_Categoria;
    public javax.swing.JLabel lab_categorias_grupo;
    public javax.swing.JLabel lab_categorias_nombreCategoria;
    private javax.swing.JLabel lab_clientes_background1;
    public javax.swing.JLabel lab_clientes_codCliente;
    public javax.swing.JLabel lab_clientes_rut;
    private javax.swing.JLabel lab_productos_background2;
    private javax.swing.JLabel lab_productos_background3;
    public javax.swing.JLabel lab_productos_codCategoria;
    public javax.swing.JLabel lab_productos_codProducto;
    public javax.swing.JLabel lab_productos_descProducto;
    public javax.swing.JLabel lab_productos_nombreProducto;
    public javax.swing.JLabel lab_productos_precioCompra;
    public javax.swing.JLabel lab_productos_precioProducto;
    public javax.swing.JLabel lab_productos_stock;
    public javax.swing.JLabel lab_productos_ubicacionBodega;
    public javax.swing.JLabel lab_productos_unidadProducto;
    public javax.swing.JLabel lab_stock_currentStock;
    private javax.swing.JLabel lab_usuarios_background;
    public javax.swing.JLabel lab_usuarios_codUser;
    public javax.swing.JLabel lab_usuarios_login;
    public javax.swing.JLabel lab_usuarios_nivelAcceso;
    public javax.swing.JLabel lab_usuarios_pass;
    public javax.swing.JLabel lab_usuarios_rut;
    public javax.swing.JLabel mod1_title;
    public javax.swing.JPasswordField pass_usuarios_pass;
    public javax.swing.JTable table_clientes;
    public javax.swing.JTable table_productos;
    public javax.swing.JTable table_productos1;
    public javax.swing.JTable table_stock;
    public javax.swing.JTable table_usuarios;
    public javax.swing.JTextField txt_categorias_borrado;
    public javax.swing.JTextField txt_categorias_codCategoria;
    public javax.swing.JTextField txt_categorias_descCategoria;
    public javax.swing.JTextField txt_categorias_grupo;
    public javax.swing.JTextField txt_categorias_nombreCategoria;
    public javax.swing.JTextField txt_clientes_codUser1;
    public javax.swing.JTextField txt_clientes_rut;
    public javax.swing.JTextField txt_productos_codCategoria;
    public javax.swing.JTextField txt_productos_codProducto;
    public javax.swing.JTextField txt_productos_descProducto;
    public javax.swing.JTextField txt_productos_nombreProducto;
    public javax.swing.JTextField txt_productos_precioCompra;
    public javax.swing.JTextField txt_productos_precioProducto;
    public javax.swing.JTextField txt_productos_stock;
    public javax.swing.JTextField txt_productos_ubicacionBodega;
    public javax.swing.JTextField txt_productos_unidadProducto;
    public javax.swing.JTextField txt_stock_newStock;
    public javax.swing.JTextField txt_usuarios_codUser;
    public javax.swing.JTextField txt_usuarios_login;
    public javax.swing.JTextField txt_usuarios_rut;
    // End of variables declaration//GEN-END:variables

}
